// import React
import { useReducer } from "react";

// import Next
import Head from "next/head";

// import state
import { AppContext, initialState } from "@/state";
import { mainReducer } from "@/state/reducers";

// import components
import AppLayout from "@/layouts/AppLayout";
import TodoList from "@/components/todoList";

// import style
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const [state, dispatch] = useReducer(mainReducer, initialState);

  return (
    <>
      <Head>
        <title>Next - Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContext.Provider value={{ state, dispatch }}>
        <AppLayout>
          <main className={styles.Home}>
            <TodoList />
          </main>
        </AppLayout>
      </AppContext.Provider>
    </>
  );
}
