// import React
import { useContext } from "react";

// import Next
import Head from "next/head";
import Link from "next/link";

// import state
import { AppContext } from "@/state";

// import components
import Navbar from "@/components/navbar";
import TodoList from "@/components/todoList";

// import style
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const { state, dispatch } = useContext(AppContext);

  return (
    <>
      <Head>
        <title>Next - Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/todo.svg" />
      </Head>

      {state.username ? (
        <main className={styles.Home}>
          <Navbar />
          <TodoList />
        </main>
      ) : (
        <div className={styles.login}>
          <h1>Please log in</h1>
          <Link href="/login">Go to Login</Link>
        </div>
      )}
    </>
  );
}
