import { useState, useContext } from "react";
import { useRouter } from "next/router";
import { AppContext } from "@/state";

// import Next
import Head from "next/head";

import { signInWithPopup } from "firebase/auth";
import { auth, provider } from "@/plugins/firebase";

import styles from "@/styles/Login.module.scss";

export default function Login() {
  const router = useRouter();

  const { dispatch } = useContext(AppContext);

  const [input, setInput] = useState("");

  const onHandleInput = (e) => setInput(e.target.value);

  const onHandleSubmit = (e) => {
    e.preventDefault();

    dispatch({ type: "SET_USERNAME", payload: input });

    router.push("/");
  };

  const onHandleGoogleAuth = async () => {
    const res = await signInWithPopup(auth, provider);

    dispatch({ type: "SET_USERNAME", payload: res.user.displayName });
  };

  return (
    <>
      <Head>
        <title>Next - Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/todo.svg" />
      </Head>
      <form className={styles.Login} onSubmit={onHandleSubmit}>
        <h1>Log in</h1>
        <input
          type="text"
          value={input}
          onChange={onHandleInput}
          placeholder="Username"
        />
        <input type="submit" value="Login" />
        OR
        <input
          type="button"
          value="Login with Google"
          onClick={onHandleGoogleAuth}
        />
      </form>
    </>
  );
}
